### ISSUE TITLE
Request: gtk4-classic ?

### ISSUE THREAD

**Issue by ignace72** [lah7/gtk3-mushrooms#100]
Hello everyone.     
Is there a gtk4-classic planned?      
I'm in no hurry, it's just that without my high-contrast window borders, it's hard to distinguish the window separation.      
Thanks and have a nice day.

**Comment by lah7** [comment]
Sorry, **no plans!** Personally, I have no incentive to adopt GTK 4, never mind patch it. I'm just keeping what we have _rolling_ for any minor GTK 3 updates and avoiding GTK 4 applications. 

GTK 4 feels like it's increasingly designed for the GNOME desktop, so I feel like it's a lost course trying to _workaround_ their design language under _more traditional_ environments like XFCE and MATE. 

If anyone is interested in tackling a "classic" GTK 4, by all means please do create a new project and let us know.

See also: https://github.com/lah7/gtk3-classic/discussions/63

> 🎉  _Issue 100 - nice!_ 🎉

**Comment by MorsMortium** [comment]
Just to disable CSD https://codeberg.org/MorsMortium/GTK4-NoCSD
