### ISSUE TITLE
Request: Don't drop primary selection on unselect [patch included]

### ISSUE THREAD

**Issue by haarp** [lah7/gtk3-mushrooms#103]
### What should be patched?

At some point many years ago, GTK started breaking X convention and the Law of Least Astonishment by clearing X's Primary Selection when text was deselected. This is unexpected and WRONG. Other toolkits do not share this behavior.

See https://gitlab.gnome.org/GNOME/gtk/-/issues/317

This behavior can be patched out.

### Screenshots

not a visual issue

### Commits

The aforementioned bug report has patches for this behavior. With these, the primary selection will not be cleared on text deselect. I have rebased them to modern GTK. See [here](https://gitlab.gnome.org/GNOME/gtk/-/issues/317#note_1816540).

Thanks a lot! :)

**Comment by lah7** [comment]
I had thought the middle click pasting seemed inconsistent - did think it was _supposed to_ paste whatever was on the clipboard. This clears it up. Wouldn't be the first time GTK broke middle-click behaviour though (#34)

Thanks for the patches! I've added them into this project. Seems to work as expected, surprisingly a useful feature now that I now understand how it works!

Just to be sure, please test the latest `gtk3-classic` on your end, then I'll tag up a new release.

**Comment by haarp** [comment]
I'm using the Gentoo ebuild from khoverlay. Paused the build, dropped the patch in, continued. The patch works! Thanks!

One issue I noticed just now: in `textview` areas (such as Xed edit area), it won't clear the primary selection on unselect, but it will modify the primary selection when the (previously unselected) text is edited. Strange I never noticed this before. This is an issue with the patch tho, not with gtk3-classic. Still, much better than before.
