### ISSUE TITLE
Notebook tabs duplicate mouse scroll

### ISSUE THREAD

**Issue by luigifab** [lah7/gtk3-mushrooms#47]
I have reimplemented (copy/paste) the notebook tabs mouse scroll in [my program](https://github.com/luigifab/awf-extended/blob/0617a20adad96b56b2dd8d5ae1b92da18b802e26/src/awf.c#L1749) some time ago,
and now with [notebook_wheel_scroll.patch](https://github.com/lah7/gtk3-classic/blob/master/notebook_wheel_scroll.patch), when I scroll, there are two scroll event in one.

Is someone know if there is a simple way to prevent my event if current GTK version is compiled with the patch?

(compiled with debian testing with GTK 3.24.23)

**Comment by luigifab** [comment]
Strangely, the problem does not occur for `mate-appearance-properties`.
The scroll works for `caja` tabs, `transmission` preferences tabs, `geany` preferences tabs, but not for `geany` document tabs.

**Comment by lah7** [comment]
I'm not proficient at C or GTK to understand why other applications seem to have no problem co-existing with this feature. The patch 66b65775822c46e07f5b2f30036010d06dbcbad4 is based on old code similar to what GTK did back in the day.

I'd recommend analysing code from other projects to see how/if they handle the scroll event differently that could be used to improve your application.

* **MATE Terminal**: https://github.com/mate-desktop/mate-terminal/commit/8d2eb0898154f2624e2ae34039169f307a3411a5 &  https://github.com/mate-desktop/mate-terminal/commit/622e2d1272bf2d7a99d147482ae6a51b0a77f188
* **Pluma**: https://github.com/mate-desktop/pluma/commit/a31a8facfba9693f7337631dfa305c64a5663e2e
* **Caja**: https://github.com/mate-desktop/caja/commit/9f2c966a28fd54fe3fcd8ae4d9330270e7673051
* **MATE Control Center**: https://github.com/mate-desktop/mate-control-center/commit/b931a8f99fc07cf860819507e18546bb9583a2f1
* (Taken from https://ubuntu-mate.community/t/gtk3-regressions-from-a-gtk2-perspective/19511?u=lah7)

The patch could add an environment to disable it, similar to [`GTK_CSD`](https://github.com/lah7/gtk3-classic/blob/8c8796458180a5b771f3d31e101ce59daee70cd0/csd__server-side-shadow.patch#L9-L10) to turn it off per-app / globally. Alternately, your application could add such environment variable / preference option to turn off the behaviour.

Regarding Geany, it works when scrolling over the GtkNotebook background, but not over the tab widgets themselves. I think the button and labels block the event. Not sure. I hacked it for myself long ago (but never upstreamed) at https://github.com/lah7/geany/commit/5bfad0da637836b63d087b791e7b26ebcb512580.

**Comment by luigifab** [comment]
Good catch! I found by reading previous links, when I copy/pasted `capplet_dialog_page_scroll_event_cb` from _mate-desktop/mate-control-center_, I removed the `return true/false`. I added it again, and problem is fixed. So I didn't say anything.

Nice tip for Geany!

**Comment by lah7** [comment]
I actually just ran into this today with Pluma's document tabs (latest, Arch), even though it seemed fine before under Ubuntu. Maybe we'll need to add an environment variable to disable it for certain apps.

**Comment by luigifab** [comment]
For Geany, it's fixed with v2.0.0!
