### ISSUE TITLE
Add css class for smaller status bar

### ISSUE THREAD

**Issue by luigifab** [lah7/gtk3-mushrooms#48]
I downloaded Ubuntu Mate 21.10 and installed gtk3-classic with [lah7 ppa](https://launchpad.net/~lah7/+archive/ubuntu/gtk3-classic).
I installed [my theme](https://github.com/luigifab/human-theme) from [my ppa](https://launchpad.net/~luigifab/+archive/ubuntu/packages).

For [appearance__smaller-statusbar.patch](https://github.com/lah7/gtk3-classic/blob/master/appearance__smaller-statusbar.patch), is it possible to add a css class for the `statusbar` node?

Because my theme render a small statusbar without gtk3-classic, and with gtk3-classic, the statusbar is 2x smaller.
With a css class, I can update theme to works with and without gtk3-classic.

Current result:
![image](https://user-images.githubusercontent.com/31816829/148371808-e864cc71-6f12-43ba-9ab3-0391a603159a.png)

Expected result:
![image](https://user-images.githubusercontent.com/31816829/148372525-ca3f83c5-e054-4985-845f-ce0c771a9166.png)

**Comment by lah7** [comment]
Pull requests welcome, if it's possible. I'd suggest a class name of `classic`.

Have you tried adding `!important` in the theme's CSS? Not sure for certain if that'll work. E.g.
```css
statusbar {
    margin: 5px !important;
}
```

**Comment by luigifab** [comment]
If I remember `!important` is not allowed with GTK.
Sure, I can make a PR, first I will search how .ui file works... #50
