### ISSUE TITLE
Black background, no theme

### ISSUE THREAD

**Issue by amerlyq** [lah7/gtk3-mushrooms#49]
### Bug Description

Default theme (Adwaita) is ignored.
Everything is black.
No config in ~/.config/gtk-3.0/settings.ini
Default config in /usr/share/gtk-3.0/settings.ini

ArchLinux:

- install gtk3-classic-noatk-64
- install gnome-themes-extra
- install pavucontrol
- run pavucontrol

### Expected Behaviour

White background, etc. as usual with "gtk3" installed.
Maybe I haven't configured some additionally required settings somewhere?
But I can't found any related info. 

### Screenshots

![2022-01-07-183852_1171x529_scrot](https://user-images.githubusercontent.com/5730096/148578474-c7017b96-b813-4883-848d-3b2d0520c791.png)

### Environment

 - OS: ArchLinux (latest)
 - Desktop Environment: None / XMonad 
 - gtk3-classic Version: gtk3-classic-noatk-64 3.24.30-1

**Comment by lah7** [comment]
`gtk3-classic-noatk-64` isn't our package. Please try `gtk3-classic` from the AUR (or [grab a copy from the release page](https://github.com/lah7/gtk3-classic/releases/tag/3.24.30-2))

**Comment by amerlyq** [comment]
Sorry, I overlooked the "Maintiner" line in AUR and only looked into "url" key.
You package as-is works as expected, thanks.

FYI: after comparing PKGBUILD files and rebuilding ~10 times I had found the perpetrator -- library "sassc" was removed from "makedepends", and adding it back avoids black background everywhere.

Can "gtk3-classic" work without "libsassc"?
I.e. can we avoid black background even if library removed?

**Comment by lah7** [comment]
No worries, glad you found the culprit!

`sassc` (depends on `libsassc`) is required to build themes at `gtk/theme/Adwaita/` and `gtk/theme/HighContrast/` which compiles `.scss` files into `.css`, which is a pretty standard thing to do in web/theme development.

You could pre-compile these SCSS files into CSS using `sassc` (or other SASS compiler) in that directory and rip out `sassc` from the build system. I personally think it's unnecessary and wouldn't accept such changes here, but it's possible to do if `gtk3-classic-noatk-64` is looking to slim down dependencies.

**Comment by amerlyq** [comment]
Aha! That's it. 
So, this app/lib isn't statically compiled into gtk3, and only used once during build.
In that case always having it in PKGBUILD does not hurt that much.

Thanks for the tip on how to overcome similar issues for other packages too.
It had gone clean out of my head, for what purpose sassc could by used by GTK, and how to workaround it.
