### ISSUE TITLE
Request: Focus and outline

### ISSUE THREAD

**Issue by luigifab** [lah7/gtk3-mushrooms#59]
### What should be patched?

With GTK 3, the `outline` is not always displayed when a button, a scale or anything else has focus.
It seems that is was displayed after pressing a navigation key (left, top, right, bottom, tab...) or?

In my theme, I replaced some `outline` with `border`.
But this is not easy everywhere, because there is no `border-offset` (only `outline-offset`).

### Screenshots
GTK 2.24:
![image](https://user-images.githubusercontent.com/31816829/150647679-82a6fb5f-d69c-4576-ba78-3bf54ebf805d.png)

GTK 3.24:
![image](https://user-images.githubusercontent.com/31816829/150647713-3724e640-473b-4f32-8770-15953e0fb485.png)

GTK 3.24 after pressing right/left arrows:
![image](https://user-images.githubusercontent.com/31816829/150647692-956c07c0-da97-49f9-97bb-7ca84197d20c.png)

### Commits

I don't know.

**Comment by luigifab** [comment]
I think this is `focus-visible`.

![image](https://user-images.githubusercontent.com/31816829/151873174-d033c50f-4e53-4cd2-b00c-b985340d3653.png)

When application start, default value is `FALSE`.
From [GTK 3.24](https://github.com/GNOME/gtk/blob/ab45bde94c7bbd140b12fa0dd6203f7b98d1a715/gtk/gtkwindow.c#L6364):
![image](https://user-images.githubusercontent.com/31816829/151874145-b4a85654-1399-450e-87b6-81e4896283ca.png)

I will try to compile by adding a new env var here.

**Comment by lah7** [comment]
Some possibly related commits for `focus-visible`:

* https://github.com/GNOME/gtk/commit/2ba9c4b4a7d9ffc3161e2db1774743182a365d99
* https://github.com/GNOME/gtk/commit/c9bfd12d2fd0d67d87171719c9237abe941a73cd
* Blame: https://github.com/GNOME/gtk/blame/ab45bde94c7bbd140b12fa0dd6203f7b98d1a715/gtk/gtkwindow.c

---

I think it's more a theme thing. If it [follows CSS style rules](https://www.tutorialrepublic.com/css-tutorial/css-outline.php), `outline-style`, `outline-offset` and `outline-color` should control how it overlays the focused control, but some themes might use `border` which would affect spacing.

The second screenshot shows the outline very faint there, so the behaviour isn't broken. I confirm that random GTK apps under Breeze theme (Disks, file browser, Meld, jstest-gtk) do show the focused control initially (also confirmed in #65).

When I first saw this issue, I was thinking that it was a request to bring back this GTK+2 feel on focused controls:

![image](https://user-images.githubusercontent.com/13032135/152339699-6b9464a8-0fe7-4e4c-935d-caa0e53284cf.png)

A quick test on Ubuntu MATE 16.04 (GTK2), reveals nothing different with regards to initial focus behaviour. Pressing tab and/or arrow keys (depending what is focused) shows the outline, dependent on theme.
