### ISSUE TITLE
Recommendation: Use gtk3-filechooser-icon-view Patch

### ISSUE THREAD

**Issue by brocashelm** [lah7/gtk3-mushrooms#67]
Hello, I saw there's a fork of GTK's filechooser that fixes the infamous bug and would like to suggest this patch be integrated into your builds. There's already an AUR build for Arch GNU/Linux, but it otherwise requires building from source.

https://github.com/Dudemanguy/gtk

Thank you.

**Comment by luigifab** [comment]
It seems that there is "only" [one commit](https://github.com/Dudemanguy/gtk/commits?author=Dudemanguy).

**Comment by Impeta** [comment]
I don't mean to rush, but has anything been done yet about this? I would love if this could be applied on, so to save the trouble of many others on installing xdg-portal's KDE counterpart just for the appropriate thumbnails and not feel a jarring unnoticeable contrast of Gtk and QT.

**Comment by mid-kid** [comment]
It's not incredibly hard to apply this patch on top of gtk3-classic, the main issue being that they make the exact same changes with slightly different code in places, so gtk3-filechooser-icon-view needs to be adapted to remove those.

The reason I wouldn't add it on top of gtk3-classic is twofold: it requires extra setup (glib-thumbnailer + tumbler), and it is just very very very buggy. More often than not it crashes my firefox when trying to save a file.

**Comment by lah7** [comment]
Thanks for the recommendation and comments. I agree with @mid-kid's comment, it wouldn't be wise to include it here.

This project is _supposed_ to patch GTK 3 in a way that restores classic GTK look & feel. You can of course make changes to your copy of the AUR package and add lines that unpatch our conflicting patch then apply their diff.

**Comment by mid-kid** [comment]
I've recently published my patchset, along with a modified filechooser icon view patch, if anyone is interested: https://github.com/mid-kid/gentoo-config/blob/master/patches/x11-libs/gtk%2B:3/9001-gtk3-filechooser-icon-view.patch
