### ISSUE TITLE
GNOME file manager has incorrect transparency and lacks user directories

### ISSUE THREAD

**Issue by fulalas** [lah7/gtk3-mushrooms#71]
Is there a variable we can set to solve the corners being broken (no transparency)? See:
![broken](https://user-images.githubusercontent.com/27843666/161216975-1d550ca3-6659-4464-b067-2e424628c894.png)

Also, as you can see above GNOME file manager doesn't show XDG user directories. Is there a variable we can set to revert this?

This is the expected result (rounded corners and user directories):
![expected](https://user-images.githubusercontent.com/27843666/161216996-a329b87f-d109-4c42-8b96-27ded6521e8c.png)

Thanks! :)

**Comment by lah7** [comment]
For the sidebar, you can drag-and-drop the missing folders back, otherwise the likely patch causing that is `file-chooser__places-sidebar.patch`. If you're running Arch, you can exclude the patch by commenting (`#`) it out in the `series` file and run `makepkg`.

For the window corners, you can try setting `export GTK_CSD=1` and/or `export GTK_RELAX_RGBA=1` in the Terminal and then executing `gnome-files` (or whatever the executable name is). If it works, those environment variables can be added to the application launcher (not sure what environment you're using, but they should be a "Edit Menu" option somewhere)

    GTK_CSD=1 gnome-files

**Comment by fulalas** [comment]
> For the sidebar, you can drag-and-drop the missing folders back,

I see. But this is not the same, right? The bookmark entries go after the horizontal line and they can be removed. I can't undo this patch because the GTK3 build is used in a distro (Porteus) I work on and it's shared among different Desktop Environments.

> For the window corners, you can try setting export GTK_CSD=1 and/or export GTK_RELAX_RGBA=1

Yeah, I tried but it doesn't work. I'm not sure which patch is breaking the transparency.

**Comment by lah7** [comment]
You're right, it's technically not the same. I think the patch's intention is so XDG directories are not "forced" upon in the GTK file picker.

Haven't heard of Porteus - a quick search didn't reveal anything about their `gtk3` package. I wouldn't recommend a distro to replace GTK3 with these patches unless none of the users run GNOME or any GNOME/CSD applications. 

It might be a CSD bug, like some of GNOME's 40.0 versions are affected by other unrelated issues (#32). If other file managers are an option: there's Nemo, Caja, Thunar.

**Comment by fulalas** [comment]
I'm one of Porteus developers :) There's no information about our GTK3 package because the team is really-really small and we haven't released version 5 (the first one that will ship with your GTK3 patches -- thank you very much!).

The double title bar issue I can see if I don't export `GTK_CSD=1`. Initially I thought it would be a bug in the GNOME build scripts for Slackware and I even opened an issue there: https://github.com/slackport/gfs/issues/5

So because this is not for me, but for many different users, shipping another file manager is not an option. Also, it doesn't affect just nautilus (GNOME's file manager) but gnome-console as well, among other applications. If there is no practical solution I'd rather put the original GTK3 package back just for the GNOME module.

Thanks!

**Comment by lah7** [comment]
I take no credit for the majority of the patches - just keeping them rolling with GTK3 upstream. I'm also not very familiar with the codebase, so pull requests are always welcome for fixes.

They are intended for "classic" desktops like MATE, XFCE, etc, so running under GNOME is not supported. It would probably upset their developers if users sent bug reports their way not realising their GTK3 was patched.

I'd agree to ship the original GTK3. Any users wanting anything featured here can install this and _keep all the pieces if it breaks_ We can add instructions here if necessary.

**Comment by fulalas** [comment]
I think you're 100% right. And I noticed that you put some information about GNOME in the main page, which is nice. I'm fine if you want to close this issue.

Thanks for the support! :)
