### ISSUE TITLE
PKGBUILD: Suggested dependency changes

### ISSUE THREAD

**Issue by lah7** [lah7/gtk3-mushrooms#73]
As suggested by [comment](https://aur.archlinux.org/packages/gtk3-classic#comment-864720):

> +1: please kindly enable the following dependencies, to be at parity with the repo version of [gtk3](https://archlinux.org/packages/?q=gtk3):
>
>    [libcolord](https://archlinux.org/packages/?q=libcolord) (meson: colord=yes)
>    [tracker3](https://archlinux.org/packages/?q=tracker3) (x86_64) (meson: tracker3=yes) (there is no lib32-tracker3 as of now but can be selectively added to only 64-bit build).
>
>Also please add the two cherry-picked patches as in the repo version [3.24.33-3](https://github.com/archlinux/svntogit-packages/commit/b7367fe4379951de745d663fe13468b1217b7daf) (adds legacy icons and fixes [epiphany FTBFS](https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/4610)).

* Optionally build with `colord` if installed.
* Optionally build with `tracker3` if installed (64-bit only).
* Add a couple of patches.

---

I'd prefer this package didn't introduce unnecessary dependencies unless it is fixing a problem. If it's possible to keep them strictly optional during build time, then that's OK. Users (and myself) prefer this package for being less bloated.

**Comment by jonathonf** [comment]
Just as a data point, noone should be building packages against gtk3-classic (packages should be built against repo packages in a clean build environment), so a patch fixing a FTBFS against GTK3 isn't something that needs to be included.

**Comment by lah7** [comment]
That's true, thanks for the tip! The "legacy icons" patch appears to be included with GTK+ 3.24.34 [according to their NEWS](https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-3-24/NEWS#L4), so that's not needed either. 

So, this task is just changing the build parameter `colord=no` to `colord=auto` to enable support if the user happens to have that package installed. This doesn't work for `tracker3=auto` (which doesn't seem essential)
