### ISSUE TITLE
PKGBUILD: Drop 32-bit support?

### ISSUE THREAD

**Issue by lah7** [lah7/gtk3-mushrooms#74]
A couple of users mentioned about splitting the `pkgbase` so the 32-bit version isn't unnecessarily built.

* https://aur.archlinux.org/packages/gtk3-classic#comment-801051
* https://aur.archlinux.org/packages/gtk3-classic#comment-864715

I myself don't use `lib32-gtk3-classic` neither. I'd be happy to drop it if nobody uses/needs this package. Someone in the community could maintain a separate `lib32-gtk3-classic` AUR package if there is a need to keep it.

**Comment by robson-66** [comment]
I already proposed it over a year ago https://aur.archlinux.org/packages/gtk3-classic#comment-801051

**Comment by jonathonf** [comment]
I personally don't see any reason for it - PKGBUILDs are not there for consumption by AUR helpers, and having lib32 support in the same place means halving the PKGBUILD maintenance burden.

**Comment by lah7** [comment]
I'm going to go ahead and drop the `lib32-gtk3-classic` package. For reasons:

* `lib32-gtk3-classic` doesn't build for GTK+ 3.24.36.
   * Strangely, I can't build `lib32-gtk3` from official repos either despite having same make dependencies.

          gtk/gdk/meson.build:328:2: ERROR: Dependency "gobject-introspection-1.0" not found, tried pkgconfig and cmake
* `lib32-gtk3` in the official repo is maintained by "Orphan". Not a good sign.
* Few dependants on `lib32-gtk3`, I would guess the majority of Arch users don't _really_ need it as it's mostly optional.
* Ease maintenance for me. I never used/tested `lib32-gtk3-classic`.
* Faster compiling (2x) from AUR for everyone.
    * _🌍  Saves the planet and energy bills, I guess 😄_

----

If any user **does** need a classic patched `lib32-gtk3`, they are welcome to use the last one: [`lib32-gtk3-classic` 3.24.35](https://github.com/lah7/gtk3-classic/releases/tag/3.24.35), or switch to [`lib32-gtk3`](https://archlinux.org/packages/multilib/x86_64/lib32-gtk3/).

Of course, any one is welcome to create a new `lib32-gtk3-classic` AUR package and maintain a patched 32-bit version.
