### ISSUE TITLE
Double border tittle and button

### ISSUE THREAD

**Issue by huyhoang8398** [lah7/gtk3-mushrooms#78]
I get Double border tittle and button in XUbuntu 22.04 again

**Comment by lah7** [comment]
Duplicate of #32. Pull requests are welcome to fix the issue.

At least with Ubuntu 21.10, [the patch was supposedly excluded.](https://github.com/lah7/gtk3-classic/issues/32#issuecomment-1004281485) Maybe the builds for 22.04 did not?
