### ISSUE TITLE
Breakage with `glib2` 2.74.0

### ISSUE THREAD

**Issue by HanabishiRecca** [lah7/gtk3-mushrooms#79]
### Bug Description

Using `glib2` 2.74.0 (currently in Arch testing repo) all GTK3 apps can't run and throw such error message:
```
$ firefox
[2402, Main Thread] ###!!! ASSERTION: g_log_set_writer_func() called multiple times: 'glib assertion', file /build/firefox/src/firefox-104.0.2/toolkit/xre/nsSigHandlers.cpp:164
ExceptionHandler::GenerateDump cloned child 2424
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
ExceptionHandler::WaitForContinueSignal waiting for continue signal...
[1] 2402 trace trap (core dumped) firefox
```
Rebuilding does not fix the issue.
Using official `gtk3` Arch package all works fine, so this is `gtk3-classic` issue for sure.

### Expected Behaviour

Apps should work.

### Environment

 - OS: Arch Linux
 - Desktop Environment: Plasma 5.25.90
 - gtk3-classic Version: 3.24.34

**Comment by lah7** [comment]
Can confirm, thanks! Will test each patch to see which one causes the problem.

**Comment by lah7** [comment]
Found the suspect!

    fixes__atk-bridge-errors.patch

`firefox` works again when `gtk3-classic` is built without this patch (commented out in `PKGBUILD` and `series`). [A script helps automate this testing.](https://github.com/lah7/gtk3-classic/blob/master/scripts/test-exclude-each-patch.sh)

It looks like the patch is no longer needed, I'll remove it and push an update.

**Comment by HanabishiRecca** [comment]
Yes, seems to be fixed.

_Offtopic: my request in the AUR package comment was ignored. Is it necessary to create an issue here?_

**Comment by lah7** [comment]
No problem. Yes, please do for future issues - the repository works better for discussion/upvoting and can reference later. I've created one for your suggestion at #80.
