### ISSUE TITLE
CSD minimize, maximize, close buttons exists despite unset GTK_CSD

### ISSUE THREAD

**Issue by Flashwalker** [lah7/gtk3-mushrooms#82]
### Bug Description

CSD minimize, maximize, close buttons exists despite GTK_CSD=0  
### UPD: despit `unset GTK_CSD`
Apps affected: eog, geary

### Expected Behaviour

No CSD minimize, maximize, close buttons

### Screenshots

![image](https://user-images.githubusercontent.com/2188215/198390465-df2db48d-ffc9-4693-932c-1aaf84a3946c.png)

### Environment

 - OS: Pop_Os! 22.04
 - Desktop Environment: xfce 
 - gtk3-classic Version: 3.24.33-2~classic~22.04

**Comment by lah7** [comment]
That's expected. From the README:

> You can enable CSDs by setting `GTK_CSD=0` environment variable (or `GTK_CSD=1` to force CSDs on each GTK3 window).

Despite the contrary, it's the presence of the `GTK_CSD` environment variable is what enables them. Setting it to `1` apparently forces them on every window.

You'll want to remove that variable like so:

    unset GTK_CSD

That said, disabling CSD _might_ be buggy with newer GNOME apps (#32). Personally, I downgraded/pinned them to their older version. Your mileage may vary. Consider alternate apps, like Eye of MATE instead of Eye of GNOME.

**Comment by Flashwalker** [comment]
Noup, unsetting doesn't helps.
And i found that almost all gnome apps affected: baobab, gnome-system-monitor, gnome-disks, gnome-calendar, gnome-calculator, gnome-logs, nautilus, org.gnome.Weather, celluloid

**Comment by mid-kid** [comment]
in `.config/gtk-3.0/settings.ini`:
```
gtk-decoration-layout = menu:
```

**Comment by Flashwalker** [comment]
> gtk-decoration-layout = menu:

Noup, doesn't helps

**Comment by mid-kid** [comment]
works for me ¯\\\_(ツ)_/¯

**Comment by Flashwalker** [comment]
Recently GNOME gayvelopers changed theming. Ruining as always

**Comment by leuchtrakete666** [comment]
works for me also. its important to set the file to `ro`. otherwise its overwritten on new login.

**Comment by Flashwalker** [comment]
well, i still have `gtk-decoration-layout=menu:` line in file and it doesn't helps

**Comment by leuchtrakete666** [comment]
remove the `:`

**Comment by Flashwalker** [comment]
> remove the `:`

just tested, no luck

**Comment by mid-kid** [comment]
I just switched to wayland, and I'm seeing exactly what you're saying. Maybe it's because of that?

**Comment by Flashwalker** [comment]
> I just switched to wayland, and I'm seeing exactly what you're saying. Maybe it's because of that?

don't know, i'm on X

**Comment by exuvo** [comment]
Flashwalker if you are starting your programs from a graphical menu make sure you `unset GTK_CSD` somewhere early like .xinitrc or /etc/X11/xinit/xinitrc.d so it applies globally. Wayland should have somewhere similar for you mid-kid.
In a terminal `unset GTK_CSD` followed by starting a gtk3 program in the same terminal session should work.

**Comment by Flashwalker** [comment]
@exuvo 
> In a terminal `unset GTK_CSD` followed by starting a gtk3 program in the same terminal session should work.

Noup, i tried it.
```
unset GTK_CSD && gnome-calendar
```
CSD buttons still exists

**Comment by dreirund** [comment]
For me it works that my window manager (`xfwm4`) does decorate the window, but for this I had to `unset GTK_CSD`.

**Comment by dreirund** [comment]
> Noup, i tried it.
> 
> ```
> unset GTK_CSD && gnome-calendar
> ```

I think gnome now is at GTK4 (but I don't know how fast your distribution has catched up; I with Artix Linux have it catched up); can you check the dependencies to verify that this is really a GTK*3* app and not a GTK*4* app?

`gtk3-classic` of course does not work with GTK4.

**Comment by Flashwalker** [comment]
@dreirund  
it is GTK3  
`GTK_DEBUG=interactive gnome-calendar`  
![2023-08-02_23-57-10](https://github.com/lah7/gtk3-classic/assets/2188215/40a1d22b-13aa-4c6e-a216-52495efadbef)

**Comment by lah7** [comment]
I just checked my Ubuntu VM and installed `gtk3-classic` via PPA. I'm not sure of the problem. By default, with an up-to-date Ubuntu MATE **22.04**, under **Xorg**, `gnome-calendar` looks like this:

![GTK_CSD_unset](https://github.com/lah7/gtk3-classic/assets/13032135/655e316d-9165-4555-8d1d-b907a1754f89)

Yuck, double controls (#32), but at least the window border is working. Equivalent to `unset GTK_CSD`.

**Then with CSDs enabled** via `export GTK_CSD=0`, that works as expected:

![GTK_CSD_0](https://github.com/lah7/gtk3-classic/assets/13032135/011ca14a-c875-416a-bd39-350f22212c2b)

[I clarified the README](https://github.com/lah7/gtk3-classic#client-side-decorations-only-on-xorg) as the way it was originally documented was starting to confuse me.

Please could you confirm the installed package versions and session type?

    dpkg -l | grep '~classic' | awk '{print $2,$3}'
    env | grep SESSION_TYPE

**Comment by Flashwalker** [comment]
@lah7 
```sh
$ dpkg -l | grep '~classic' | awk '{print $2,$3}'
gir1.2-gtk-3.0:amd64 3.24.33-2~classic~22.04
gtk-update-icon-cache 3.24.33-2~classic~22.04
libgail-3-0:amd64 3.24.33-2~classic~22.04
libgtk-3-0:amd64 3.24.33-2~classic~22.04
libgtk-3-bin 3.24.33-2~classic~22.04
libgtk-3-common 3.24.33-2~classic~22.04
libgtk-3-dev:amd64 3.24.33-2~classic~22.04

$ env | grep SESSION_TYPE
XDG_SESSION_TYPE=x11
```

**Comment by lah7** [comment]
I wonder if there is a "local" copy of GTK 3 installed that's overriding the system package. Check with this command:

    ldd /usr/bin/gnome-calendar | grep gtk-3

The output should be something like:

    libgtk-3.so.0 => /lib/x86_64-linux-gnu/libgtk-3.so.0 (0x00007f5c52310000)

If the path starts with `/usr/local` (or something else), then that version of GTK 3 will need removing. This _could_ happen if GTK was once compiled and installed with a command like `make install`.

**Comment by dreirund** [comment]
> *it is GTK3*

I checked my Arch Linux dependencies, and it depends on gtk3 packages as well as on gtk4 packages. GTK4 example:

`gnome-calendar` &rarr; `evolution-data-server  geoclue  geocode-glib-2  gsettings-desktop-schemas  libadwaita  libedataserverui4  libgweather-4  libsoup3`  
`libadwaita` &rarr; `gtk4  libgtk-4.so=1-64`

And `ldd /usr/bin/gnome-calendar | grep gtk` gives gtk4 as well (and no gtk3):  
```
	libgtk-4.so.1 => /usr/lib/libgtk-4.so.1 (0x00007f6138600000)
	libwebkitgtk-6.0.so.4 => /usr/lib/libwebkitgtk-6.0.so.4 (0x00007f6133800000)
	libjavascriptcoregtk-6.0.so.1 => /usr/lib/libjavascriptcoregtk-6.0.so.1 (0x00007f6130e00000)
```

So it seems gtk4 in my case.

**Comment by lah7** [comment]
[Ubuntu 22.04 ships with `gnome-calendar` 41.2](https://packages.ubuntu.com/jammy/gnome-calendar), which is built with GTK+3. If I'm understanding this issue correctly, @Flashwalker expects to see the window border, but is seeing the CSD header instead. Almost like it's not using the patched GTK+3 library.

Arch Linux's `gnome-calendar` (currently 44.1) is built on GTK+4, so CSD headers is expected there.

**Comment by Flashwalker** [comment]
> ... If I'm understanding this issue correctly, @Flashwalker expects to see the window border, but is seeing the CSD header instead...

Actually i have the window border with `unset GTK_CSD`, but also have the CSD
![2023-08-04_23-29-01](https://github.com/lah7/gtk3-classic/assets/2188215/13635679-065c-4d78-a0bd-ebfc8e1f5df8)

**Comment by lah7** [comment]
Unfortunately, this is expected behaviour. See #32.

To summarize, there is a library (`libhandy`) that apps might use, and that library renders window controls into the app. GTK+3 alone can't patch this out.

Workarounds could be to:
* Downgrade/pin an older app version.
* Set `GTK_CSD=0` for this app, so it displays as the developer intended.
* Accept defeat and find alternates
  * _Especially GNOME apps, it makes sense for _their_ apps to follow _their_ design guidelines for use on _their_ desktop._

**Comment by Flashwalker** [comment]
Oh, damn gnome vendorlock 😩
