### ISSUE TITLE
All GTK apps exit on startup with "Trace/breakpoint trap" message

### ISSUE THREAD

**Issue by GrantEdwards** [lah7/gtk3-mushrooms#84]
### Bug Description

I've been using gtk3-classic patches for several months with no issues, but today, all GTK apps started to crash on startup with the message:

    Trace/breakpoint trap

This happened on two different systems. After rebuilding gtk+3 without patches, everything works fine. I _think_ the breakage happened when Gentoo bumped from gtk+-3.24.34 to gtk+-3.24.34-r1 on Oct 10 2022. AFAICT all that change did was fix some configuration requirements for cairo:

[https://gitweb.gentoo.org/repo/gentoo.git/log/x11-libs/gtk+](https://gitweb.gentoo.org/repo/gentoo.git/log/x11-libs/gtk+)

Any ideas what could be causing this?

### Environment

 - OS: Gentoo Linux
 - Desktop Environment: openbox
 - gtk3-classic Version:  3.24.34

The ebuild file is here:
[https://github.com/gentoo-mirror/khoverlay/tree/master/x11-libs/gtk3-classic-patches](https://github.com/gentoo-mirror/khoverlay/tree/master/x11-libs/gtk3-classic-patches)

**Comment by GrantEdwards** [comment]
I rolled back the gtk+ upgrade and it made no difference.

 A couple days prior to the gtk+ upgrade. I see that glib upgraded from 2.72.3 to 2.74.1-r1. I now suspect this is the same as [issue 79](https://github.com/lah7/gtk3-classic/issues/79). Trying to figure out how to test that...

**Comment by GrantEdwards** [comment]
This is indeed a duplicate of issue 79.

Manually removing `fixes__atk-bridge-errors.patch` after installing the gtk3-classic-patches ebuild mentioned above fixes the problem.

**Comment by GrantEdwards** [comment]
Trying to close this issue....

**Comment by GrantEdwards** [comment]
Trying to close this issue.

**Comment by khumba** [comment]
Hi, I am responsible for the ebuild here (and am not affiliated with the project, I just deeply appreciate it, thank you @lah7).  I got caught by this today, and have just pushed an updated 3.24.34.2 ebuild to the overlay, so you can pull that down however you prefer.

For what it's worth, the fixed gtk3-classic was released almost two months ago.  My process for checking for newer releases of software in my overlay was mistakenly ignoring gtk3-classic, but I've fixed that now so ebuild updates should be more prompt.  My apologies for the hassle.

**Comment by lah7** [comment]
Glad to hear it's all working again! 

For what it's worth, shall we add instructions for your Gentoo ebuild to the README?

**Comment by khumba** [comment]
Sure, that would be great.  I'll write something up and open a PR.
