### ISSUE TITLE
Error while building gtk3-classic 3.24.35

### ISSUE THREAD

**Issue by robson-66** [lah7/gtk3-mushrooms#87]
As the title says, I have this error while building

```gtk+-3.24.35/gdk/wayland/meson.build:1:0: ERROR: Non-existent build file 'gdk/wayland/cursor/meson.build'```

**Comment by lah7** [comment]
Same here. Even if I exclude all the patches, I can't get past this error:

```c++
Compiler stderr:
 In file included from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/limits.h:26,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/include-fixed/limits.h:203,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/include-fixed/syslimits.h:7,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/include-fixed/limits.h:34,
                 from /home/user/Desktop/gtk3-classic/src/build/meson-private/tmp8r_77yue/testfile.c:4:
/usr/include/features.h:412:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
  412 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
```

Tried from similar warnings I could find on the web, but no luck:
```diff

 build()
 {
-	CFLAGS+=" -DG_ENABLE_DEBUG -DG_DISABLE_CAST_CHECKS"
+	CFLAGS+=" -DG_DISABLE_CAST_CHECKS  -D_FORTIFY_SOURCE=2"
 
 	# 64-bit
 	arch-meson gtk+-$_gtkver build \
@@ -120,6 +120,7 @@ build()
 		-D colord=auto \
 		-D demos=true \
 		-D examples=false \
+		-D introspection=true \
 		-D tests=false \
 		-D installed_tests=false
 	ninja -C build
```

Probably something wrong with our build commands/flags. Changes to `gtk3` upstream for reference:

* https://github.com/archlinux/svntogit-packages/commit/bd2d14c1c2a0d8d33f1ada6047665b98b3bf8d52
* https://github.com/archlinux/svntogit-packages/commit/ec12847fb811add133b399aaf0916c96eb03862e

**Comment by robson-66** [comment]
I think the man found a solution.
https://bbs.archlinux.org/viewtopic.php?pid=2070549#p2070549

**Comment by robson-66** [comment]
This error is on the side of `GTK` source files, not PKGBUILD.
https://github.com/Homebrew/homebrew-core/pull/116612

EDIT.
After adding the `gdk/wayland/cursor/meson.build` file, the build proceeds without any problems.

**Comment by lah7** [comment]
Thank you for investigating this!
