### ISSUE TITLE
`GTKM_INSERT_EMOJI=1` doesn't works in Mousepad

### ISSUE THREAD

**Issue by Flashwalker** [lah7/gtk3-mushrooms#88]
I set `GTKM_INSERT_EMOJI=1` in `~/.xprofile`
But no entry in context menu appears in Mousepad

**Comment by lah7** [comment]
The option doesn't appear under regular GTK 3 either. It's very likely that Mousepad uses its own custom (but identical looking) context menu overriding GTK's default.

The environment variable works, since MATE's Pluma text editor correctly shows "Insert Emoji" in the context menu.
