### ISSUE TITLE
Ubuntu 22.10 support

### ISSUE THREAD

**Issue by daemonspudguy** [lah7/gtk3-mushrooms#91]
This seems like a big oversight. Ubuntu 22.10 has been out for months and the PPA is still for 22.04 only.

**Comment by lah7** [comment]
You might be the first 22.10 user here! There has been no demand for interim releases.  I suspected most users who use this under Ubuntu will prefer the LTS releases for stability in their desired "classic" desktop metaphor.

Packaging this for Ubuntu is time consuming, not to mention [it was a challenging to begin with](https://github.com/lah7/gtk3-classic/issues/43). When we introduced Ubuntu packages, 21.10 was used to help support 20.04 LTS. It takes a while to prepare, build and **test** against these patches as Ubuntu use their own patches (that may conflict) and the release might ship an earlier GTK+ version.

So, the main reason is that it is not worth the effort for releases with 9 months support.  In 2 months, 23.04 will be out so the time spent packaging for an even _nicher_ niche does not fulfil me with joy. 

That said, the README and PPA description is updated to clarify this project only packages for LTS releases.
