### ISSUE TITLE
Remove the window border for GnuBiff.

### ISSUE THREAD

**Issue by ignace72** [lah7/gtk3-mushrooms#97]
Hello to all.
The patch added me also borders on the notification of GnuBiff.
Is there a solution to remove the borders only on GnuBiff?
Thanks in advance.

**Comment by lah7** [comment]
We need details - do you have a screenshot? What desktop environment are you using (MATE, XFCE)? GnuBiff looks like an applet for a panel.

Since you're on Arch, exclude patches by placing a `#` at the start of the line in the `series` file, and then run `makepkg` as usual.

As a guess, maybe it's this patch you should comment out:

    appearance__fix_black_border.patch

**Comment by ignace72** [comment]
Hello, lah7.
It's the same on Xfce as on Kde Plasma (I was there today).
I don't understand what you are asking me.
I installed GNUBiff with AUR, so I didn't do anything by hand.
As you can see, on Kde the border doesn't look bad with the contrasting border, but I still need to center the applet in height.
Here is a capture with Xfce and today with Kde :
[https://ignace72.eu/wp-content/uploads/2023/05/GNUBiff-gtk3-classic.webp](url)
[https://ignace72.eu/wp-content/uploads/2023/05/GNUBiff.webp](url)
Good evening to you.

**Comment by lah7** [comment]
Hello, thanks for the screenshot.  I haven't used GNUBiff before, so I installed to check.

| gtk3 | gtk3-classic | 
| --- | --- | 
| ![Screenshot_20230508_204333](https://user-images.githubusercontent.com/13032135/236918241-ea43a5ef-2ffb-44df-b2b9-246a3acd8f58.png) | ![image](https://user-images.githubusercontent.com/13032135/236920924-0c6e8aa5-57d7-48a8-9c7a-4655aef2f242.png)

I see the problem now.  Not sure which patch is responsible for this. Environment variables like `GTK_CSD=0` had no effect.

You can fix it for KDE, which has "Windows Rules" that can be configured to disable the window title and frame for this application, like so:

![Screenshot_20230508_210051](https://user-images.githubusercontent.com/13032135/236922004-b1e1528d-bbe0-4385-95cb-f53aa73b2452.png)

This might work under XFCE too if `kwin` is your window manager.

**Comment by ignace72** [comment]
Arf, my savior, having stopped at KDE 3, I couldn't know about this feature.
There, it's much better like that.
It's cleaner.
Thank you very much.
Have a nice evening.
